# Generated by Django 4.2.4 on 2023-10-11 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bookings",
            table="bookings",
        ),
        migrations.AlterModelTable(
            name="payment",
            table="payment",
        ),
        migrations.AlterModelTable(
            name="traveler",
            table="traveler",
        ),
    ]
