# Generated by Django 4.2.4 on 2024-02-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
