# Generated by Django 4.2.4 on 2023-10-18 04:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0003_alter_bookings_drop_off_id_alter_bookings_pick_up_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="drop_off_id",
            new_name="drop_off",
        ),
        migrations.RenameField(
            model_name="bookings",
            old_name="pick_up_id",
            new_name="pick_up",
        ),
        migrations.RenameField(
            model_name="bookings",
            old_name="seat_id",
            new_name="seat",
        ),
        migrations.RenameField(
            model_name="bookings",
            old_name="trip_id",
            new_name="trip",
        ),
        migrations.RenameField(
            model_name="bookings",
            old_name="updated_time",
            new_name="updated_date",
        ),
        migrations.RenameField(
            model_name="bookings",
            old_name="user_id",
            new_name="user",
        ),
    ]
