# Generated by Django 4.2.4 on 2023-10-24 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0004_rename_drop_off_id_bookings_drop_off_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookings",
            name="seat",
        ),
    ]
