# Generated by Django 4.2.4 on 2023-10-24 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0022_alter_routes_duration"),
        ("normal_user", "0005_remove_bookings_seat"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SeatAvailability",
            new_name="BookedSeats",
        ),
        migrations.AlterModelTable(
            name="bookedseats",
            table="booked_seats",
        ),
    ]
