# Generated by Django 4.2.4 on 2023-10-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0006_rename_seatavailability_bookedseats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookedseats",
            name="traveller_dob",
            field=models.DateField(default="2023-04-23"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookedseats",
            name="traveller_gender",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bookedseats",
            name="traveller_name",
            field=models.CharField(default="fsdfsff", max_length=255),
            preserve_default=False,
        ),
    ]
