# Generated by Django 4.2.4 on 2023-10-24 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0008_alter_bookings_total_amount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Traveler",
        ),
    ]
