# Generated by Django 4.2.4 on 2023-11-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "bus_owner",
            "0023_amenities_status_buslayout_status_seatdetails_status_and_more",
        ),
        ("normal_user", "0009_delete_traveler"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookedseats",
            name="trip",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bus_owner.trip",
            ),
            preserve_default=False,
        ),
    ]
