# Generated by Django 4.2.4 on 2023-11-21 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0010_bookedseats_trip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user_id",
        ),
    ]
