# Generated by Django 4.2.4 on 2023-11-21 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0011_remove_payment_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="booking_id",
            new_name="booking",
        ),
    ]
