# Generated by Django 4.2.4 on 2023-12-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0013_rename_review_tittle_userreview_review_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercomplaints",
            name="response",
            field=models.TextField(default="none"),
            preserve_default=False,
        ),
    ]
