# Generated by Django 4.2.4 on 2023-12-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0014_usercomplaints_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercomplaints",
            name="response",
            field=models.TextField(blank=True),
        ),
    ]
