# Generated by Django 4.2.4 on 2023-12-12 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0015_alter_usercomplaints_response"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercomplaints",
            name="response",
        ),
    ]
