# Generated by Django 4.2.4 on 2023-12-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0017_usercomplaints_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercomplaints",
            name="complaint_for",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
