# Generated by Django 4.2.4 on 2023-12-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0020_usercomplaints_complaint_for_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreview",
            name="review_body",
            field=models.TextField(),
        ),
    ]
