# Generated by Django 4.2.4 on 2023-12-14 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0022_userreview_bookind_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userreview",
            old_name="bookind_id",
            new_name="booking_id",
        ),
    ]
