# Generated by Django 4.2.4 on 2023-12-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0023_rename_bookind_id_userreview_booking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercomplaints",
            name="complaint_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
