# Generated by Django 4.2.4 on 2023-12-20 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("normal_user", "0024_usercomplaints_complaint_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreview",
            name="review_for",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewer",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userreview",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="writer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
