# Generated by Django 4.2.4 on 2023-12-20 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0025_rename_bookind_id_userreview_booking_id"),
        ("normal_user", "0025_userreview_review_for_alter_userreview_user_id"),
    ]

    operations = []
