# Generated by Django 4.2.4 on 2023-10-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100, null=True)),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("aadhaar_no", models.CharField(max_length=100, null=True)),
                ("msme_no", models.CharField(max_length=100, null=True)),
                ("extra_charges", models.FloatField(null=True)),
                ("role", models.SmallIntegerField(default=2)),
                ("status", models.SmallIntegerField(default=0)),
                ("user_details_status", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
