# Generated by Django 4.2.4 on 2024-01-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_manage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAndOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                ("otp", models.IntegerField(max_length=6, null=True)),
                ("counter", models.SmallIntegerField(default=0)),
                ("status", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "email_and_otp",
            },
        ),
    ]
