# Generated by Django 4.2.4 on 2023-10-10 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account_manage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
