# Generated by Django 4.2.4 on 2024-01-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_manage", "0002_emailandotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailandotp",
            name="otp",
            field=models.IntegerField(null=True),
        ),
    ]
