# Generated by Django 4.2.4 on 2024-01-08 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("account_manage", "0004_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notifications",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="notifications",
            table="notifications",
        ),
    ]
