# Generated by Django 4.2.4 on 2024-01-11 05:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account_manage", "0004_niotifications"),
        ("account_manage", "0004_notifications"),
    ]

    operations = []
