# Generated by Django 4.2.4 on 2024-01-15 04:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account_manage", "0005_notifications_created_date_and_more"),
        ("account_manage", "0006_delete_niotifications"),
    ]

    operations = []
