# Generated by Django 4.2.4 on 2023-10-10 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_name", models.CharField(max_length=100)),
                ("plate_no", models.CharField(max_length=100)),
                ("status", models.SmallIntegerField(default=0)),
                ("bus_type", models.SmallIntegerField(default=2)),
                ("bus_ac", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bus",
            },
        ),
        migrations.CreateModel(
            name="Locations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "locations",
            },
        ),
        migrations.CreateModel(
            name="Routes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_point", models.CharField(max_length=255)),
                ("end_point", models.CharField(max_length=255)),
                ("via", models.CharField(max_length=255)),
                ("distance", models.DecimalField(decimal_places=5, max_digits=7)),
                ("duration", models.TimeField()),
                ("travel_fare", models.DecimalField(decimal_places=5, max_digits=7)),
                ("status", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "routes",
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("status", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "bus_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bus_owner.bus"
                    ),
                ),
                (
                    "route_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_owner.routes",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeatDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=50)),
                ("seat_type", models.SmallIntegerField(default=0)),
                ("deck", models.SmallIntegerField(default=0)),
                ("seat_cost", models.DecimalField(decimal_places=5, max_digits=7)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bus_owner.bus"
                    ),
                ),
            ],
            options={
                "db_table": "seat_details",
            },
        ),
        migrations.CreateModel(
            name="PickUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_stop", models.CharField(max_length=255)),
                ("arrival_time", models.TimeField()),
                ("landmark", models.CharField(max_length=255)),
                ("status", models.SmallIntegerField(default=0)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_owner.locations",
                    ),
                ),
            ],
            options={
                "db_table": "pick_up",
            },
        ),
        migrations.AddField(
            model_name="locations",
            name="routes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bus_owner.routes"
            ),
        ),
        migrations.CreateModel(
            name="DropOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_stop", models.CharField(max_length=255)),
                ("arrival_time", models.TimeField()),
                ("landmark", models.CharField(max_length=255)),
                ("status", models.SmallIntegerField(default=0)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_owner.locations",
                    ),
                ),
            ],
            options={
                "db_table": "drop_off",
            },
        ),
        migrations.CreateModel(
            name="Amenities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emergency_no", models.SmallIntegerField(default=0)),
                ("water_bottle", models.SmallIntegerField(default=0)),
                ("charging_point", models.SmallIntegerField(default=0)),
                ("usb_port", models.SmallIntegerField(default=0)),
                ("blankets", models.SmallIntegerField(default=0)),
                ("pillows", models.SmallIntegerField(default=0)),
                ("reading_light", models.SmallIntegerField(default=0)),
                ("toilet", models.SmallIntegerField(default=0)),
                ("snacks", models.SmallIntegerField(default=0)),
                ("tour_guide", models.SmallIntegerField(default=0)),
                ("cctv", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bus_owner.bus"
                    ),
                ),
            ],
            options={
                "db_table": "amenities",
            },
        ),
    ]
