# Generated by Django 4.2.4 on 2024-01-23 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

location_data = "bus_owner.locationdata"
bus_owner_bus = "bus_owner.bus"
bus_owner_routes = "bus_owner.routes"
class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_name", models.CharField(max_length=100)),
                ("plate_no", models.CharField(max_length=100)),
                ("status", models.SmallIntegerField(default=0)),
                ("bus_seat_type", models.SmallIntegerField(default=2)),
                ("bus_type", models.SmallIntegerField(default=0)),
                ("bus_ac", models.SmallIntegerField(default=0)),
                ("bus_details_status", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bus",
            },
        ),
        migrations.CreateModel(
            name="LocationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "location_data",
            },
        ),
        migrations.CreateModel(
            name="Routes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("via", models.CharField(max_length=255)),
                ("distance", models.DecimalField(decimal_places=3, max_digits=10)),
                ("duration", models.DecimalField(decimal_places=3, max_digits=10)),
                ("travel_fare", models.DecimalField(decimal_places=3, max_digits=10)),
                ("status", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "end_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="end_point",
                        to=location_data,
                    ),
                ),
                (
                    "start_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_point",
                        to=location_data,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "routes",
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("status", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=bus_owner_bus
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=bus_owner_routes,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trip",
            },
        ),
        migrations.CreateModel(
            name="StartStopLocations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq_id", models.IntegerField()),
                ("arrival_time", models.TimeField()),
                ("arrival_date_offset", models.IntegerField(default=0)),
                ("departure_time", models.TimeField()),
                ("departure_date_offset", models.IntegerField(default=0)),
                ("status", models.SmallIntegerField(default=0)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=location_data,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to=bus_owner_routes,
                    ),
                ),
            ],
            options={
                "db_table": "start_stop_locations",
            },
        ),
        migrations.CreateModel(
            name="SeatDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=50)),
                ("seat_ui_order", models.IntegerField()),
                ("seat_type", models.SmallIntegerField(default=0)),
                ("deck", models.SmallIntegerField(default=0)),
                ("seat_cost", models.DecimalField(decimal_places=3, max_digits=10)),
                ("status", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=bus_owner_bus
                    ),
                ),
            ],
            options={
                "db_table": "seat_details",
            },
        ),
        migrations.CreateModel(
            name="PickAndDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_stop", models.CharField(max_length=255)),
                ("arrival_time", models.TimeField()),
                ("landmark", models.CharField(max_length=255)),
                ("status", models.SmallIntegerField(default=0)),
                (
                    "route",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=bus_owner_routes,
                    ),
                ),
                (
                    "start_stop_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="bus_owner.startstoplocations",
                    ),
                ),
            ],
            options={
                "db_table": "pick_and_drop",
            },
        ),
        migrations.CreateModel(
            name="BusLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.SmallIntegerField()),
                ("status", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=bus_owner_bus
                    ),
                ),
            ],
            options={
                "db_table": "bus_layout",
            },
        ),
        migrations.CreateModel(
            name="Amenities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emergency_no", models.SmallIntegerField(default=0)),
                ("water_bottle", models.SmallIntegerField(default=0)),
                ("charging_point", models.SmallIntegerField(default=0)),
                ("usb_port", models.SmallIntegerField(default=0)),
                ("blankets", models.SmallIntegerField(default=0)),
                ("pillows", models.SmallIntegerField(default=0)),
                ("reading_light", models.SmallIntegerField(default=0)),
                ("toilet", models.SmallIntegerField(default=0)),
                ("snacks", models.SmallIntegerField(default=0)),
                ("tour_guide", models.SmallIntegerField(default=0)),
                ("cctv", models.SmallIntegerField(default=0)),
                ("status", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=bus_owner_bus
                    ),
                ),
            ],
            options={
                "db_table": "amenities",
            },
        ),
    ]
