# Generated by Django 4.2.4 on 2023-10-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routes",
            name="distance",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name="routes",
            name="travel_fare",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name="seatdetails",
            name="seat_cost",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
