# Generated by Django 4.2.4 on 2023-10-17 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("normal_user", "0003_alter_bookings_drop_off_id_alter_bookings_pick_up_id"),
        ("bus_owner", "0003_locationdata_pickanddrop_startstoplocations_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DropOff",
        ),
        migrations.DeleteModel(
            name="Locations",
        ),
        migrations.DeleteModel(
            name="PickUp",
        ),
        migrations.AddField(
            model_name="startstoplocations",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bus_owner.locationdata"
            ),
        ),
        migrations.AddField(
            model_name="startstoplocations",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bus_owner.routes"
            ),
        ),
        migrations.AddField(
            model_name="pickanddrop",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bus_owner.locationdata"
            ),
        ),
        migrations.AddField(
            model_name="pickanddrop",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bus_owner.routes"
            ),
        ),
    ]
