# Generated by Django 4.2.4 on 2023-10-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0004_delete_dropoff_delete_locations_delete_pickup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatdetails",
            name="seat_ui_order",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
