# Generated by Django 4.2.4 on 2023-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bus_owner",
            "0006_rename_arival_date_offset_startstoplocations_arrival_date_offset_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="bus_details_complete",
            field=models.SmallIntegerField(default=0),
        ),
    ]
