# Generated by Django 4.2.4 on 2023-10-18 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "bus_owner",
            "0011_rename_bus_id_trip_bus_rename_route_id_trip_route_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="pickanddrop",
            old_name="arrival_time_offset",
            new_name="arrival_time",
        ),
    ]
