# Generated by Django 4.2.4 on 2023-10-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0012_rename_arrival_time_offset_pickanddrop_arrival_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="startstoplocations",
            name="departure_date_offset",
            field=models.IntegerField(default=0),
        ),
    ]
