# Generated by Django 4.2.4 on 2023-10-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0013_startstoplocations_departure_date_offset"),
    ]

    operations = [
        migrations.AddField(
            model_name="startstoplocations",
            name="departure_time",
            field=models.TimeField(default="12:00:00"),
            preserve_default=False,
        ),
    ]
