# Generated by Django 4.2.4 on 2023-10-18 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0016_buslayout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bus",
            old_name="bus_type",
            new_name="bus_seat_type",
        ),
    ]
