# Generated by Django 4.2.4 on 2023-10-18 05:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0018_bus_bus_type"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="buslayout",
            table="bus_layout",
        ),
    ]
