# Generated by Django 4.2.4 on 2023-10-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0019_alter_buslayout_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="buslayout",
            name="bus",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bus_owner.bus",
            ),
            preserve_default=False,
        ),
    ]
