# Generated by Django 4.2.4 on 2023-10-19 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0020_buslayout_bus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routes",
            name="end_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end_point",
                to="bus_owner.locationdata",
            ),
        ),
        migrations.AlterField(
            model_name="routes",
            name="start_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="start_point",
                to="bus_owner.locationdata",
            ),
        ),
    ]
