# Generated by Django 4.2.4 on 2023-10-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0021_alter_routes_end_point_alter_routes_start_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routes",
            name="duration",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
