# Generated by Django 4.2.4 on 2023-11-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0022_alter_routes_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenities",
            name="status",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="buslayout",
            name="status",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="seatdetails",
            name="status",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="startstoplocations",
            name="status",
            field=models.SmallIntegerField(default=0),
        ),
    ]
