# Generated by Django 4.2.4 on 2023-11-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0025_alter_startstoplocations_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickanddrop",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pick_and_drop",
                to="bus_owner.routes",
            ),
        ),
    ]
