# Generated by Django 4.2.4 on 2023-11-09 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0027_pickanddrop_start_stop_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pickanddrop",
            name="location",
        ),
    ]
