# Generated by Django 4.2.4 on 2023-11-09 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0029_alter_pickanddrop_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickanddrop",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bus_owner.routes",
            ),
        ),
    ]
