# Generated by Django 4.2.4 on 2023-11-10 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0030_alter_pickanddrop_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickanddrop",
            name="start_stop_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stops",
                to="bus_owner.startstoplocations",
            ),
        ),
    ]
