# Generated by Django 4.2.4 on 2023-10-10 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CouponDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coupon_code", models.CharField(max_length=20)),
                ("coupon_name", models.CharField(max_length=100)),
                ("coupon_description", models.TextField()),
                ("coupon_eligibility", models.SmallIntegerField(default=0)),
                ("coupon_dob", models.DateField()),
                ("valid_till", models.DateTimeField()),
                ("discount", models.IntegerField()),
                ("status", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "coupon_details",
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_email", models.CharField(max_length=254)),
                ("to_email", models.CharField(max_length=254)),
                ("status", models.SmallIntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "email",
            },
        ),
        migrations.CreateModel(
            name="RefundPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refund_percentage", models.FloatField()),
                ("refund_timeframe", models.IntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "refund_policy",
            },
        ),
        migrations.CreateModel(
            name="CouponAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminstrator.coupondetails",
                    ),
                ),
            ],
            options={
                "db_table": "coupon_availability",
            },
        ),
    ]
