# Generated by Django 4.2.4 on 2023-12-18 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0024_alter_startstoplocations_route"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adminstrator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.SmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "coupon_history",
            },
        ),
        migrations.RemoveField(
            model_name="coupondetails",
            name="coupon_dob",
        ),
        migrations.AddField(
            model_name="coupondetails",
            name="bus_owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coupondetails",
            name="coupon_availability",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coupondetails",
            name="one_time_use",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coupondetails",
            name="trip",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bus_owner.trip",
            ),
        ),
        migrations.AlterField(
            model_name="coupondetails",
            name="valid_till",
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name="CouponAvailability",
        ),
        migrations.AddField(
            model_name="couponhistory",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adminstrator.coupondetails",
            ),
        ),
        migrations.AddField(
            model_name="couponhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
