# Generated by Django 4.2.4 on 2024-01-25 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bus_owner", "0001_initial"),
        ("adminstrator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="trip",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bus_owner.trip",
            ),
        ),
    ]
