# Generated by Django 4.2.4 on 2023-12-18 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminstrator", "0002_couponhistory_remove_coupondetails_coupon_dob_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupondetails",
            old_name="bus_owner",
            new_name="user",
        ),
    ]
